name: CI

on:
  push:
    tags:
    - '*'
  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: erlangpack/github-action@v1
      with:
        hex-api-key: ${{ secrets.HEX_API_KEY }}    
